// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QaAutomation.Infrastructure.Persistence;

#nullable disable

namespace QaAutomation.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QaAutomationDbContext))]
    [Migration("20260623055533_AddScannerReviewTools")]
    partial class AddScannerReviewTools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QaAutomation.Core.Scans.DetectedElement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessibleName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("AccessibleRole")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AssociatedLabel")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double?>("BoundingHeight")
                        .HasColumnType("float");

                    b.Property<double?>("BoundingWidth")
                        .HasColumnType("float");

                    b.Property<double?>("BoundingX")
                        .HasColumnType("float");

                    b.Property<double?>("BoundingY")
                        .HasColumnType("float");

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ClassificationOverride")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CropPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DiscoveryOrder")
                        .HasColumnType("int");

                    b.Property<string>("HtmlId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("InputType")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<bool>("IsActionable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPotentiallyDestructive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ManualPreferredSelectorCandidateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameAttribute")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("PageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Placeholder")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("ReviewUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ScreenshotError")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("TestId")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("VisibleText")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ClassificationOverride");

                    b.HasIndex("IsPotentiallyDestructive");

                    b.HasIndex("ManualPreferredSelectorCandidateId");

                    b.HasIndex("UserDisplayName");

                    b.HasIndex("PageId", "DiscoveryOrder");

                    b.ToTable("DetectedElements", (string)null);
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.Scan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ActionTimeoutMilliseconds")
                        .HasColumnType("int");

                    b.Property<string>("BrowserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("CancellationRequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DetectedElementCount")
                        .HasColumnType("int");

                    b.Property<int>("DetectedPageCount")
                        .HasColumnType("int");

                    b.Property<int?>("ElementScreenshotPadding")
                        .HasColumnType("int");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("int");

                    b.Property<string>("FailureSummary")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FinalUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int?>("MaximumDetectedElements")
                        .HasColumnType("int");

                    b.Property<int?>("MaximumDiagnosticRecords")
                        .HasColumnType("int");

                    b.Property<int?>("NavigationTimeoutMilliseconds")
                        .HasColumnType("int");

                    b.Property<int?>("OverallTimeoutSeconds")
                        .HasColumnType("int");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("StartingUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ViewportHeight")
                        .HasColumnType("int");

                    b.Property<int>("ViewportWidth")
                        .HasColumnType("int");

                    b.Property<int>("WarningCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PageTitle");

                    b.HasIndex("RequestedAtUtc");

                    b.HasIndex("Status");

                    b.HasIndex("TargetId");

                    b.HasIndex("Status", "RequestedAtUtc");

                    b.HasIndex("TargetId", "Status");

                    b.ToTable("Scans", (string)null);
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.ScanDiagnostic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Method")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("StatusCode");

                    b.HasIndex("ScanId", "Category");

                    b.HasIndex("ScanId", "CreatedAtUtc");

                    b.HasIndex("ScanId", "Severity");

                    b.ToTable("ScanDiagnostics", (string)null);
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.ScannedPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DiscoveryOrder")
                        .HasColumnType("int");

                    b.Property<string>("FinalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("GeneratedDisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MainHeading")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginalPageTitle")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OriginalUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset?>("ReviewUpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<Guid>("ScanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("ScreenshotHeight")
                        .HasColumnType("int");

                    b.Property<string>("ScreenshotPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ScreenshotWidth")
                        .HasColumnType("int");

                    b.Property<string>("ThumbnailPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ReviewUpdatedAtUtc");

                    b.HasIndex("UserDisplayName");

                    b.HasIndex("ScanId", "DiscoveryOrder");

                    b.ToTable("ScannedPages", (string)null);
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.SelectorCandidate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<Guid>("ElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPreferred")
                        .HasColumnType("bit");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("SelectorType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SelectorValue")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("WasUnique")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ElementId", "Priority");

                    b.ToTable("SelectorCandidates", (string)null);
                });

            modelBuilder.Entity("QaAutomation.Core.Targets.Target", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AllowedHost")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("nvarchar(253)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("StartingUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("IsEnabled", "Environment");

                    b.ToTable("Targets", (string)null);
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.DetectedElement", b =>
                {
                    b.HasOne("QaAutomation.Core.Scans.SelectorCandidate", "ManualPreferredSelectorCandidate")
                        .WithMany()
                        .HasForeignKey("ManualPreferredSelectorCandidateId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QaAutomation.Core.Scans.ScannedPage", "Page")
                        .WithMany("Elements")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManualPreferredSelectorCandidate");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.Scan", b =>
                {
                    b.HasOne("QaAutomation.Core.Targets.Target", "Target")
                        .WithMany()
                        .HasForeignKey("TargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Target");
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.ScanDiagnostic", b =>
                {
                    b.HasOne("QaAutomation.Core.Scans.Scan", "Scan")
                        .WithMany("Diagnostics")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.ScannedPage", b =>
                {
                    b.HasOne("QaAutomation.Core.Scans.Scan", "Scan")
                        .WithMany("Pages")
                        .HasForeignKey("ScanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scan");
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.SelectorCandidate", b =>
                {
                    b.HasOne("QaAutomation.Core.Scans.DetectedElement", "Element")
                        .WithMany("SelectorCandidates")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Element");
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.DetectedElement", b =>
                {
                    b.Navigation("SelectorCandidates");
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.Scan", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("Pages");
                });

            modelBuilder.Entity("QaAutomation.Core.Scans.ScannedPage", b =>
                {
                    b.Navigation("Elements");
                });
#pragma warning restore 612, 618
        }
    }
}
